using System.Text.Json;
using System.Text.RegularExpressions;
using HarnessLauncher.Models;
using HarnessLauncher.Support;

namespace HarnessLauncher.Services;

public class ProfileManagerException : Exception
{
    public ProfileManagerException(string message) : base(message) { }

    public static readonly ProfileManagerException ProfileUnavailable =
        new("Harness 的 web profile 尚未初始化。");
    public static ProfileManagerException PluginHasNoPatchRows(string name) =>
        new($"插件 {name} 没有可识别的 bundle patch 行，无法由应用单独启停。");
}

/// <summary>
/// Direct port of ProfileManager: enumerates bundle plugins from the web
/// profile's package.json and writes the launcher overlay patch that
/// disables selected bundle rows.
/// </summary>
public sealed class ProfileManager
{
    private readonly AppPaths _paths;
    private HashSet<string> _disabledRows;

    public ProfileManager(AppPaths paths)
    {
        _paths = paths;
        _disabledRows = ReadDisabledRows(paths.Overlay);
    }

    public List<HarnessPlugin> Refresh()
    {
        _disabledRows = ReadDisabledRows(_paths.Overlay);
        var manifestPath = Path.Combine(_paths.ProfileWeb, "package.json");
        if (!File.Exists(manifestPath)) return new List<HarnessPlugin>();
        JsonElement manifest;
        try
        {
            using var document = JsonDocument.Parse(File.ReadAllText(manifestPath));
            manifest = document.RootElement.Clone();
        }
        catch
        {
            AppLogger.Log(AppLogger.Level.Error, "plugins", "Could not parse web profile package.json");
            return new List<HarnessPlugin>();
        }

        var bundleNames = NestedStringArray(manifest, "dsh", "profile", "bundles");
        var dependencies = TryGet(manifest, "dependencies", out var deps) &&
            deps.ValueKind == JsonValueKind.Object ? deps : (JsonElement?)null;

        var plugins = new List<HarnessPlugin>();
        foreach (var packageName in bundleNames)
        {
            if (dependencies is null || !dependencies.Value.TryGetProperty(packageName, out _)) continue;
            var packageManifest = PackageManifest(packageName);
            if (packageManifest is null) continue;
            var patchPath = NestedString(packageManifest.Value, "dsh", "bundle", "patch");
            if (patchPath is null) continue;
            var patchFile = Path.GetFullPath(Path.Combine(PackageDirectory(packageName), patchPath));
            var rows = PatchRowIds(patchFile);
            if (rows.Count == 0) continue;
            var version = TryGet(packageManifest.Value, "version", out var v) &&
                v.ValueKind == JsonValueKind.String ? v.GetString()! : "unknown";
            plugins.Add(new HarnessPlugin
            {
                Id = packageName,
                Version = version,
                BundleRowIds = rows,
                IsDisabled = rows.All(_disabledRows.Contains),
            });
        }
        return plugins;
    }

    public void SetEnabled(IReadOnlyList<HarnessPlugin> plugins, bool enabled)
    {
        if (plugins.Count == 0) return;
        var selectedIds = plugins.Select(p => p.Id).ToHashSet(StringComparer.Ordinal);
        var protectedRows = enabled
            ? Refresh()
                .Where(p => p.IsDisabled && !selectedIds.Contains(p.Id))
                .SelectMany(p => p.BundleRowIds)
                .ToHashSet(StringComparer.Ordinal)
            : new HashSet<string>(StringComparer.Ordinal);

        foreach (var plugin in plugins)
        {
            if (plugin.BundleRowIds.Count == 0)
            {
                throw ProfileManagerException.PluginHasNoPatchRows(plugin.Id);
            }
            if (enabled)
            {
                foreach (var row in plugin.BundleRowIds.Where(r => !protectedRows.Contains(r)))
                {
                    _disabledRows.Remove(row);
                }
            }
            else
            {
                foreach (var row in plugin.BundleRowIds)
                {
                    _disabledRows.Add(row);
                }
            }
        }
        WriteOverlay();
    }

    public string? OverlayPathIfNeeded() => _disabledRows.Count == 0 ? null : _paths.Overlay;

    public string PackageDirectory(string packageName) =>
        Path.GetFullPath(Path.Combine(_paths.ProfileWeb, "node_modules", packageName));

    public bool ProfileExists() => Directory.Exists(_paths.ProfileWeb);

    private void WriteOverlay()
    {
        if (_disabledRows.Count == 0)
        {
            if (File.Exists(_paths.Overlay)) File.Delete(_paths.Overlay);
            return;
        }

        var content = "# Generated by DeepSeek Harness. Do not edit.\n";
        foreach (var rowId in _disabledRows.OrderBy(r => r, StringComparer.Ordinal))
        {
            content += $"- id: {rowId}\n  disabled: true\n";
        }
        Directory.CreateDirectory(_paths.State);
        File.WriteAllText(_paths.Overlay, content);
    }

    private JsonElement? PackageManifest(string packageName)
    {
        var path = Path.Combine(PackageDirectory(packageName), "package.json");
        if (!File.Exists(path)) return null;
        try
        {
            using var document = JsonDocument.Parse(File.ReadAllText(path));
            return document.RootElement.Clone();
        }
        catch { return null; }
    }

    private static bool TryGet(JsonElement element, string name, out JsonElement value)
    {
        value = default;
        return element.ValueKind == JsonValueKind.Object && element.TryGetProperty(name, out value);
    }

    private static string? NestedString(JsonElement element, params string[] path)
    {
        var current = element;
        foreach (var key in path)
        {
            if (!TryGet(current, key, out current)) return null;
        }
        return current.ValueKind == JsonValueKind.String ? current.GetString() : null;
    }

    private static IReadOnlyList<string> NestedStringArray(JsonElement element, params string[] path)
    {
        var current = element;
        foreach (var key in path)
        {
            if (!TryGet(current, key, out current)) return Array.Empty<string>();
        }
        if (current.ValueKind != JsonValueKind.Array) return Array.Empty<string>();
        return current.EnumerateArray()
            .Where(item => item.ValueKind == JsonValueKind.String)
            .Select(item => item.GetString()!)
            .ToList();
    }

    private static HashSet<string> ReadDisabledRows(string overlayPath)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);
        if (!File.Exists(overlayPath)) return result;
        var lines = File.ReadAllLines(overlayPath);
        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i].Trim();
            if (!line.StartsWith("- id:")) continue;
            var id = line["- id:".Length..].Trim().Trim('\'', '"');
            if (i + 1 < lines.Length && lines[i + 1].Trim().StartsWith("disabled: true"))
            {
                result.Add(id);
            }
        }
        return result;
    }

    private static readonly Regex PatchRowPattern = new(
        @"(?m)^\s*-\s+id:\s*['""]?([A-Za-z0-9_.:-]+)['""]?\s*$", RegexOptions.Compiled);

    private static IReadOnlyList<string> PatchRowIds(string patchFile)
    {
        if (!File.Exists(patchFile)) return Array.Empty<string>();
        var text = File.ReadAllText(patchFile);
        return PatchRowPattern.Matches(text)
            .Select(match => match.Groups[1].Value)
            .ToList();
    }
}
